---
title: "Web scraping"
author: "JV"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
START <- Sys.time()
```

```{r warning=FALSE}
library(readr)
library(stringr)
library(rvest)
library(tibble)

source("Functions/read_ibestat_links.R")

directory <- getwd()
```

In IBestat.txt there are multiple links obtained by "manual" web scraping. To obtain all the links to data sets we have to use the function read.ibesat.links that create a data frame whit them. This will save all links ended like ".px" a kind of archive that store data and metadata and the name of the data set. 

```{r warning=FALSE}

# a IBestat.txt hi ha els links on hi ha mes links per descarregar les bbdd.
links_ibestat <- read_csv("Data/IBestat.txt")
links_ibestat <- links_ibestat[str_detect(links_ibestat$"Links:", "https"), ]
links_ibestat <- as.data.frame(links_ibestat)

# funció de lectura dels links, hi hem d'introduir unicament els links en format df

#links_to_download <- read.ibestat.links(links_ibestat)
links_to_download <- lectura.links.ibestat(links_ibestat)

write.csv(
  links_to_download,
  paste0(directory, "/Data/links_to_download.csv"),
  fileEncoding = "UTF-8"
)
```

Time to execute this code:

```{r include=FALSE}
END <- Sys.time()
```


```{r echo=FALSE}
print(END-START)
```


